const express=require('express');
const mongoose=require('mongoose');
const env=require('dotenv');
env.config();//to read .env file and set environment variables
const app=express();
const port=process.env.PORT;

//connect to mongodb database
mongoose
    .connect(process.env.MONGODB_URL)
        // .connect('mongodb://localhost:27017/backend')
        .then(()=>console.log("Database connected successfully"))
        .catch((err)=>console.log("Database connection failed:",err));



app.use(express.json());//middleware to parse json request body
app.use(express.urlencoded({extended:true}));//middleware to parse urlencoded request body
app.get('/',(req,res)=>{
    res.send("Welcome to the backend server");
});
const itemSchema=new mongoose.Schema({
    id:{type:Number,required:true,unique:true},
    name:{type:String,required:true,unique:true},
    email:{type:String,required:true,unique:true},
    phone:{type:Number,required:true,unique:true}
},
    {
        timestamps:true,
    }
);
const Item=mongoose.model('Item',itemSchema);
app.post('/additem',async(req,res)=>{
    try {
    const newItem={
    id:req.body.id,
    name:req.body.name,
    email:req.body.email,
    phone:req.body.phone
    
        }
        const u= await new Item(newItem);
        await u.save();
        res.status(201).json({ message: "New item added successfully",Item:newItem });
    } catch (err) {
        res.status(500).json({ message: "Internal server error" ,});
    }
});
//get all items
app.get('/getitems',async(req,res)=>{
    try { 
        const receiveditems=await Item.find({});
        res.status(200).json({items:receiveditems});
    } catch (err) {
        res.status(500).json({ message: "Internal server error" ,});
    }
});
//get item by id
app.get('/getitem/:id',async(req,res)=>{
      const receiveditem=await Item.findById(req.params.id);//this id is generated by mongodb
    try { 
        // const itemId=req.params.id;
        // const receiveditem=await Item.findOne({id:req.params.id});//using id created by us in pot method
      
        res.status(200).json({item:receiveditem});
    } catch (err) {
        res.status(500).json({ message: "Internal server error" ,});
    }   
});


app.put('/updateitem/:id',async(req,res)=>{
    try {
        const updatedItem={
            id:req.body.id,
            name:req.body.name,
            email:req.body.email,
            phone:req.body.phone
        }
        const itemId=req.params.id;
        await Item.findByIdAndUpdate(itemId,updatedItem);
        res.status(200).json({ message: "Item updated successfully",Item:updatedItem });
    } catch (err) {
        res.status(500).json({ message: "Internal server error" ,});
    }
});
//delete item by id
app.delete('/deleteitem/:id',async function(req,res){
        const deletedItem = await Item.findByIdAndDelete(req.params.id,{new:true});
        if(!deletedItem){
        res.status(500).json({ message: "Internal server error" ,});
        }
       
        res.status(200).json({ message: "Item deleted successfully",Item:deletedItem });

});

app.listen(port,()=>{
    console.log(`server is running on url: http://localhost:${port}`);
});


//cluster name:staffmanagement
//username:dharshinik23cse_db_user
//password:qF7Sdkq1u7QgqA8C 